package('concerto-core')
    set_homepage('https://github.com/ConcertoEngine/ConcertoCore')
    set_description('Concerto engine core library')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/ConcertoCore.git')
    add_versions('2024.08.08', '42e134d3b0c18ee6b826bd960d5d71056feacf07')
    add_deps("nlohmann_json")

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
