package('concerto-core')
    set_homepage('https://github.com/ConcertoEngine/ConcertoCore')
    set_description('Concerto engine core library')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/ConcertoCore.git')
    add_versions('2024.06.03', '9eebc30a4f90c256d0fd9cdafac29e3aae26333c')
    add_deps("nlohmann_json")

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
