package('Concerto')
    set_homepage('https://github.com/ConcertoEngine/Concerto')
    set_description('Concerto engine')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/Concerto.git')
    add_versions('2023.08.10+2', '9c4b320a1334ab9249e92ee9b456288103e979b2')
    add_deps('ConcertoGraphics')

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
