package('Concerto')
    set_homepage('https://github.com/ConcertoEngine/Concerto')
    set_description('Concerto engine')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/Concerto.git')
    add_versions('2023.08.10+3', '96bac0ff4d703a287444e403e1817712aa22a87c')
    add_deps('ConcertoGraphics')

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
