package('ConcertoCore')
    set_homepage('https://github.com/ConcertoEngine/ConcertoCore')
    set_description('Concerto engine core library')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/ConcertoCore.git')
    add_versions('2024.03.03', 'dd5d2cdaed937b3a99a3dcd2279164018b0e36c3')
    add_deps("nlohmann_json")

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
