package('ConcertoGraphics')
    set_homepage('https://github.com/ConcertoEngine/ConcertoGraphics')
    set_description('Concerto engine graphics library')
    set_license('MIT')
    set_kind('library')
    add_urls('https://github.com/ConcertoEngine/ConcertoGraphics.git')
    add_versions('2023.08.09', 'cd9850b5d0da0063ce599c5208664bb0e56a7ea4')
    add_deps('ConcertoCore', 'vulkan-loader', 'vulkan-memory-allocator', 'glm', 'stb', 'glfw', 'imgui')

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)
